name: UI E2E (Robot + Browser)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Install Playwright browser binaries
        run: rfbrowser install

      - name: Run tests
        env:
          MAXEX_USERNAME: ${{ secrets.MAXEX_USERNAME }}
          MAXEX_PASSWORD: ${{ secrets.MAXEX_PASSWORD }}
        run: |
          robot -d results -v ENV:dev tests

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results
